In [4]:
import numpy as np
M= np.array([[2, 4,2,5,1], 
    [1, 6, 9, -1, -5],
    [-4, 8, 12, 16, -20],
    [15, 0, 15, 0, 2]])
print(M[:,0]) 
print(M[:,3]) 
print(M[:,-1]) 

[ 2  1 -4 15]
[ 5 -1 16  0]
[  1  -5 -20   2]
