In [1]:

# importing numpy library
import numpy as np
  
# create numpy 2d-array
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 5, 9]])
  
print("Printing the Original square array:\n",
      m)
  
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)
  
# printing eigen values
print("Printing the Eigen values of the given square array:\n",
      w)
  
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",
      v)

Printing the Original square array:
 [[1 2 3]
 [4 5 6]
 [1 5 9]]
Printing the Eigen values of the given square array:
 [ 1.36846584e+01 -5.34127118e-16  1.31534156e+00]
Printing Right eigenvectors of the given square array:
 [[-0.27148068 -0.40824829 -0.05675667]
 [-0.62857049  0.81649658 -0.83345229]
 [-0.72883289 -0.40824829  0.54966895]]
