In [1]:
import numpy as np
mat1 = ([1,2,5],[3 ,7,8],[2, 1, 3])
mat2 = ([3, 1, 6],[5, 6, 1],[6,6, 7])
  
# This will return dot product
res = np.dot(mat1,mat2)
print(res)

[[43 43 43]
 [92 93 81]
 [29 26 34]]
