In [2]:
import numpy as np

arr = np.array([[1,3,9], [4,1,2]])

print('Original Array:\n',arr)

arr_transpose = arr.transpose()

print('Transposed Array:\n',arr_transpose)

Original Array:
 [[1 3 9]
 [4 1 2]]
Transposed Array:
 [[1 4]
 [3 1]
 [9 2]]
